project_id = "nqfltvbzqxdxsobhedci"

[functions.get-subscription-plans]
verify_jwt = false

[functions.paystack-resolve-account]
verify_jwt = true

[functions.paystack-create-recipient]
verify_jwt = true

[functions.paystack-initiate-withdrawal]
verify_jwt = true

[functions.paystack-get-banks]
verify_jwt = true
